# Generated by Django 2.2.28 on 2026-09-12 22:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_seconds', models.PositiveIntegerField(default=180)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='DebateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('A', 'AI-A(賛成派)'), ('B', 'AI-B(反対派)')], max_length=1)),
                ('content', models.TextField()),
                ('offset_seconds', models.PositiveIntegerField()),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='debate.Debate')),
            ],
            options={
                'ordering': ['offset_seconds'],
            },
        ),
    ]
