# Generated by Django 2.2.28 on 2026-09-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatemessage',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='debatemessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
