# Generated by Django 2.2.28 on 2026-09-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_auto_20260913_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatemessage',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debatemessage',
            name='turn_type',
            field=models.CharField(choices=[('question', '出題'), ('answer', '回答'), ('verdict', '判定')], default='question', max_length=10),
        ),
        migrations.AlterField(
            model_name='debatemessage',
            name='side',
            field=models.CharField(choices=[('A', 'AI-A(出題者)'), ('B', 'AI-B(回答者)')], max_length=1),
        ),
    ]
